# Generated by Django 4.2.7 on 2023-11-29 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('router1', 'Router 1 - 10.0'), ('switch1', 'Switch 1 - 15.0'), ('server1', 'Server 1 - 20.0'), ('computer1', 'Computer 1 - 5.0'), ('printer1', 'Printer 1 - 8.0'), ('access_point1', 'Access Point 1 - 12.0'), ('firewall1', 'Firewall 1 - 18.0'), ('modem1', 'Modem 1 - 25.0'), ('storage1', 'Storage 1 - 30.0'), ('camera1', 'Camera 1 - 7.0'), ('phone1', 'Phone 1 - 3.0'), ('tablet1', 'Tablet 1 - 9.0'), ('laptop1', 'Laptop 1 - 14.0'), ('smart_tv1', 'Smart TV 1 - 22.0'), ('iot_device1', 'IoT Device 1 - 17.0')], max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('final_rate', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congestion_control_app.networkdevice')),
            ],
        ),
    ]
