# Generated by Django 4.2.7 on 2023-11-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congestion_control_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='status',
            field=models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Maintenance'), ('offline', 'Offline'), ('error', 'Error')], max_length=50),
        ),
    ]
